### PR TITLE
Real data on result page

### LINKED ISSUE #212: [FEATURE]: Real data on result page
### Feature Summary

image
Show the real data based on the race result

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mauryapari**
---
 Issue #212 | Real data on the result page
---

Discord Username: @king_.bradley

## What type of PR is this? (select all that apply)

- [x] 🍕 Feature

## Description

- Added code to fetch real results from the database and show them on the result page
- Fetching the last 7 results for the same snippet and showing the user's progress in the graph.

## Related Tickets & Documents

- Related Issue #
- Closes #212 

## QA Instructions, Screenshots, Recordings
[actual result.webm](https://github.com/webdevcody/code-racer/assets/47924620/9c545937-4043-4604-af18-fee60824f36d)

## Added/updated tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by scape76** [comment]
Does it count the errors that were made during the race?

**Comment by scape76** [comment]
hey @mauryapari your pr has conflict

**Comment by mauryapari** [comment]
> Does it count the errors that were made during the race?

Hey no it does not. i can work on that.

**Comment by scape76** [comment]
> > Does it count the errors that were made during the race?
> 
> Hey no it does not. i can work on that. can i create a new task for that?

yeah, I will merge this pr and you can create a new issue

**Pull request merged**
