### PR TITLE
A very minor fix to UI profile page

### PR DESCRIPTION
**Pull request by Ragudos**
modified:   src/app/layout.tsx

---
title: Issue # |
---

Discord Username: @aaronragudos

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

If you check, there's an overflow in profile page if you have no achievements. Additionally, when a user is in landscape, the height is too fluid, so I set a min height of 50rem.

image

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by mshubitidze** [comment]
hi, this is not a minor change, changes to root layout file affects all pages
also, using min-h-[50rem] for screen height is not recommended
please create an issue and include the browser you are using and the screen resolution this issue occurs on

**Comment by Ragudos** [comment]
Ahhh, alright. I always used min-h-[value] for my works. Would it be alright to explain why it's not recommended? I'll be sure to edit it later.

**Comment by mshubitidze** [comment]
> Ahhh, alright. I always used min-h-[value] for my works. Would it be alright to explain why it's not recommended? I'll be sure to edit it later.

when setting min-h-[something] in the root layout file unless the change is tested on all pages and screen resolutions, you cannot be sure it doesn't negatively affect other pages
setting min height for a specific page, in this case profile page, if needed, is a better approach here

one more thing, i suggest you include a screenshot of what the page looks like after the changes, not just what it fixes in the description

**Comment by Ragudos** [comment]
Alright. I'll take note of those. Thank you!

**Pull request closed without merging**
