### PR TITLE
[FEATURE]: Smooth follower for race

### PR DESCRIPTION
**Pull request by laroccol**
---
title: Issue #294 | Smooth follower for race
---

Discord Username: @laroccol

## What type of PR is this? (select all that apply)

- [ x ] 🍕 Feature
- [ x ] 🧑‍💻 Code Refactor

## Description

I added a component that will smoothly follow the user as they type text. I changed the style from a background color to an underline, however this can be changed and I think it would be cool to have multiple option (underline, vertical, bg-color...).

## QA Instructions, Screenshots, Recordings

https://github.com/webdevcody/code-racer/assets/50590312/b383381e-ea52-47e0-aaa2-648f0dc45f2b

### UI accessibility concerns?

I tested the performance using chrome devtools with x4 and x6 slowdown and it was able to still perform well.

### CODE REVIEW

**Comment by scape76** [comment]
This looks really cool. But I think for now we will stick with the yellow background follows the cursor. It would be cool if a user could choose a default "cursor follower" in his profile. What do you think? If you want, I can help you with that

**Comment by scape76** [comment]
hey @laroccol. What do you think?

**Comment by laroccol** [comment]
Yes I think that is a good idea, its probably something we will have to add in db correct? If so, should I add it to the users table or do you think we should have a separate table for settings?

**Comment by scape76** [comment]
> Yes I think that is a good idea, its probably something we will have to add in db correct? If so, should I add it to the users table or do you think we should have a separate table for settings?

Can you just for now resolve your conflicts, I will merge your pr, and then we will work on this together? Also your discord name provided isn't right

**Pull request merged**
