### PR TITLE
refactor, result page error case fix

### PR DESCRIPTION
**Pull request by mshubitidze**
---
title: No Issue # | refactor, result page error case fix
---

Discord Username: @_mshub

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

- refactor footer, nav, heading, site config, icons
- add nowrap to re-race button, remove raceId column
- handle case where user navigates directly to /result page without finishing a race first
- format unformatted files

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

- no ui changes

### UI accessibility concerns?

- no

## Added/updated tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by scape76** [comment]
I think the changes in footer are not neccessary, footer can be a reusable component, so it's better to keep passing classname from parent's component. Also, Link is used to navigate across the website and it won't work pointing on a github page

**Comment by scape76** [comment]
@mshubitidze can you revert your changes in footer please?

**Comment by mshubitidze** [comment]
> @mshubitidze can you revert your changes in footer please?

hi scape, i don't believe a footer should be a reusable component, it should be defined once in the root layout file and should not change on any of the public pages
i kinda agree with the link tag, the change is unnecessary, although it gets rendered down to an <a> tag and works the same with external urls. i believe nextjs no longer recommends using <a> tag over Link for external urls anymore
i can revert the changes if you still want me to!
cheers

**Comment by scape76** [comment]
Oh, silly me. Didn't know about the Link working with external urls, is it came with the newest updates?

**Pull request merged**
