### PR TITLE
Feature: New Record Notification

### PR DESCRIPTION
**Pull request by christianlozano99**
---
[FEATURE]: New Record Notification: https://github.com/webdevcody/code-racer/issues/645
---

Discord Username: @Chris_

## What type of PR is this? (select all that apply)

- [ x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description
Since now we have a notification system, I utilized it to add the feature of sending the user a notification if they beat their previous fastest CPM and/or Accuracy.  I also added on the safeLoader function to the new feature functions and a previously existing one, getCurrentRaceResult().

## Related Tickets & Documents

- Related Issue #
- Closes https://github.com/webdevcody/code-racer/issues/645

### UI accessibility concerns?
No

## Added/updated tests?

- [ ] 👍 yes
- [x ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by phoukiethseng** [comment]
Lint complained that you used single quotes string, changing that to double quotes should fix the problem

**Comment by scape76** [comment]
@christianlozano99, please, resolve issues

**Comment by christianlozano99** [comment]
Sorry for the huge delay I had a really busy week with work.

**Comment by christianlozano99** [comment]
I am not sure why test is failing, let me know if there's a way for me to run it locally so I can identify the issue and push the fixed version.

**Comment by webdevcody** [comment]
looks good!

**Pull request merged**
