### PR TITLE
Fix: Issue #437 | #401

### LINKED ISSUE #186: [FEATURE]: Display required keymap
### Feature Summary

It's currently too hard to notice what keys need to be pressed after pressing `Enter` for a new line. 

We could display a required keymap to pass the current snippet. This needs to have UI updates at every keypress so that I can know what the next required key is.

Like this

Screenshot 2023-07-14 at 3 05 51 AM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #401: [FEATURE]: line numbers in the typing area
### Feature Summary

as a user it would be nice to have line numbers in the typing area
- line numbers should have a clear divider from the code
- current line number should be highlighted
- Extra: user should be able to choose either "normal" or "relative" either from a dropdown or a toggle
  - relative corresponds to relative line numbering
  - normal corresponds to normal line numbering

e.g. relative numbering:
Screenshot 2023-07-18 at 16 36 23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #437: [BUG]: Pressing the Enter button when it is not a newline makes too many text errors
### Description

When the 'Enter' key is pressed and it isn't a newline, the game handles this as jumping to the next available newline and leaving all skipped letters as errors in the text that must be fixed. This heavily impacts a user's score as a result.

Please see video for reference.

Ideally the 'Enter' key should just be considered as a single entered character and should only produce 1 text error. 

https://github.com/webdevcody/code-racer/assets/64496022/9d6e10e6-fdd6-4815-b1c0-8e117493f86b

### (optional) What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sudo-adduser-jordan**
---
Fix: Issue #437 | Issue #401
---

Discord Username: @sudo-adduser-jordan 

## What type of PR is this? (select all that apply)

- [ x ] 🐛 Bug Fix

## Description

-Remove Arrow Keys.
-Remove Tab.
-Enter will only create one error.
-Lock typing if there is an error.
-Remove Backspace() function call inside Enter(). (Why someone decieded to put a Backspace function call inside a key that does not backspace I have no idea).

## Related Tickets & Documents

- Closes #437
- Closes #401

## QA Instructions, Screenshots, Recordings

https://github.com/webdevcody/code-racer/assets/108599131/5c7c822c-5851-40a6-9f65-04ed88c0f8ed

### Additional Comments

I went ahead and completed this issue.
I saw it was high priority and this may be extremely confusing for some one unfamiliar with this file.

The arrow and tab keys have also been removed. 
They are not needed if we are decieding to use this functionality descriebed in this issue.
I would also prefer we don't use them as it adds a lot of extra complexity that isn't needed.

If the person assigned to this issue has any refactoring suggestions they would be welcomed.

Issue 401 may also be closed as the user will always be on the corresponding line.

### CODE REVIEW

**Comment by Ragudos** [comment]
I like that we're actually going to prevent the user from typing further if they made an error, since this is generally the reason why I added arrow keys, since a user might be super fast at typing and miss an error. And to note, I added the Backspace() function in the Enter() function only when a group of text is highlighted. If you check, when you highlight text in an IDE and press Enter, it will remove the highlighted text and go onto a new line.

Anyway, I do think it's easier to maintain, scale and implement the idea of just stopping someone from typing once they make a mistake.

**Comment by sudo-adduser-jordan** [comment]
"To note, I added the Backspace() function in the Enter() function only when a group of text is highlighted. If you check, when you highlight text in an IDE and press Enter, it will remove the highlighted text and go onto a new line."

That is true. I did not consider that. 

With the change in the issue we will no longer have to worry about it 😄

**Comment by sudo-adduser-jordan** [comment]
*Suggested by @webdevcody in discord
https://discord.com/channels/663478877355507769/1126627632461643797/1131392358869651507

**Comment by webdevcody** [comment]
I think it's worth trying this idea.  I've raced a few times just to get to the end and see I have an error, and it's very frustrating, so this might fix that entire issue.

**Pull request merged**
