### PR TITLE
Redesigned Profile Page And Achievements Section

### PR DESCRIPTION
**Pull request by aweshchoudhary**
---
title: Issue # |
---

I have redesigned the User Profile Page and Achievements Section

## Before User Profile Page
before

###  This is a dummy data screenshot and Before pushing the code, I have removed the dummy data and made this dynamic
beforeProfile
### Mobile Screenshot
localhost_3000_profile (1)

Discord Username: @aweshchoudhary

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by aweshchoudhary** [comment]
I have removed all the dummy data. And this page is fully responsive

**Comment by phoukiethseng** [comment]
I think we just display user bio directly without having to click button.

**Comment by trace2798** [comment]
Please communicate in Discord before making any more changes. This is the second time you are doing it. Also, your PR is not linked to any issue.

**Comment by aweshchoudhary** [comment]
No, @webdevcody has said in yesterday live stream to redesign of profile page will be better. This layout will not cause any style issue in futur.

**Comment by aweshchoudhary** [comment]
Sorry, I will keep that in mind I don't have much knowledge of open-source contribution. I will read all discussed issues then contribute.

**Pull request merged**
