### PR TITLE
Added class in code.tsx pre tag to wrap the whitespace by itself

### PR DESCRIPTION
**Pull request by AmanRoy007**
---
title: Issue # 599
---

Discord Username: @

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [✅ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

I have added a new class in code.tsx in pre tag to wrap whitespaces by itself , if there is a long line of text that's overflow the input it will wrap to the next line so user didn't have to scroll it by himself.

## Related Tickets & Documents

- Related Issue # https://github.com/webdevcody/code-racer/issues/599
- Closes #

## QA Instructions, Screenshots, Recordings

before fixing issue 
image

After fixing issue:
image

## Added/updated tests?

- [ ] 👍 yes
- [ ✅] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by scape76** [comment]
Personally, I would consider it as just a bad snippet and reported it. And if we say it's not, then the enter tab won't work correctly on the end of the line, as it expects us to hit a space instead, so it adds a bit of complexity where it shouldn't be. Basically with your changes it's harder to recognize a bad snippet

**Comment by scape76** [comment]
I'm closing this pr for now, feel free to ask anything

**Comment by AmanRoy007** [comment]
@scape76  Suppose if someone put a code snippet with long comment after any code line , then it will overflows to right and trying to type that code at one point you can not see the highlighted cursor.  In that case what should you will do.

**Comment by scape76** [comment]
> @scape76 Suppose if someone put a code snippet with long comment after any code line , then it will overflows to right and trying to type that code at one point you can not see the highlighted cursor. In that case what should you will do.

answered in #599

**Pull request closed without merging**
