### PR TITLE
#456 | Improved header nav UI and styling for header & footer

### LINKED ISSUE #456: [FEATURE]: Improved UI / styling for header & footer
### Feature Summary

I worked on improving the UI and styling for the header menu items and footer. Let me know if yall like it and i will submit PR :)

### Before:
Screenshot from 2023-07-20 18-37-04

Screenshot from 2023-07-20 18-37-11

[Screencast from 07-20-2023 06:25:45 PM.webm](https://github.com/webdevcody/code-racer/assets/112876685/2f87f4b8-fefc-4c56-b728-b1880381a5cc)

### After:

Screenshot from 2023-07-20 18-37-43

Screenshot from 2023-07-20 18-37-56

[Screencast from 07-20-2023 06:24:12 PM.webm](https://github.com/webdevcody/code-racer/assets/112876685/f2e90423-fc70-4149-b6fd-778e55a5b799)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sycodes95**
Discord Username: 

## What type of PR is this? (select all that apply)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description
Improved visuals of menu items in Header nav. Changed styling of header and footer.

Before: 
[Screencast from 07-20-2023 06:25:45 PM.webm](https://github.com/webdevcody/code-racer/assets/112876685/cfc5d86a-1a7b-4baa-8503-2be3952a3d0f)

Screenshot from 2023-07-20 18-37-04

Screenshot from 2023-07-20 18-37-11

After: 
[Screencast from 07-20-2023 06:24:12 PM.webm](https://github.com/webdevcody/code-racer/assets/112876685/1d44535a-a613-44c7-90e5-2789d30fe35e)

Screenshot from 2023-07-20 18-37-43

Screenshot from 2023-07-20 18-37-56

## Related Tickets & Documents

- Related Issue #456 
- Closes #456 

## Added/updated tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by Ragudos** [comment]
Hello! Please add a before and after image/screenshot or a video to show the changes, so the contributors who have write access can see the change.

**Comment by sycodes95** [comment]
> Hello! Please add a before and after image/screenshot or a video to show the changes, so the contributors who have write access can see the change.

Added in description :)

**Comment by scape76** [comment]
maybe we can leave the color of the header background on dark theme the same as the main background?

**Comment by webdevcody** [comment]
can we please make a community vote for if this change is better or if people like the other style

**Pull request merged**
