### PR TITLE
Fix: special buttons click cause unwanted behaviour #287

### LINKED ISSUE #287: [BUG]: special buttons click cause unwanted behaviour
### Description

When I am clicking on capslock / tabs / shift buttons, it causes unwanted behaviour (it types in some
characters, but what I want is:

1. on tabs produce 2 spaces
2. on caps lock I don't want it to produce anything at all
3. on shift same as 2

### (optional) What browsers are you seeing the problem on?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sudo-adduser-jordan**
---
Issue #287 |
---

Discord Username: @sudo-adduser-jordan 

## What type of PR is this? (select all that apply)

- [ x ] 🐛 Bug Fix

## Description

- Tab will produce 2 spaces
- CapsLock will not produce anything
- Shift will not produce anything
- Tab In / Shift Tab Out

https://github.com/webdevcody/code-racer/assets/108599131/4b95b474-e16d-4a38-bb57-158d94d45884

## Related Tickets & Documents

- Closes #287

## Added/updated tests?

- [ x ] 🙅 no, because they aren't needed

### CODE REVIEW

**Comment by sudo-adduser-jordan** [comment]
Updated video

**Comment by scape76** [comment]
@sudo-adduser-jordan resolve conflict please

**Comment by trace2798** [comment]
@sudo-adduser-jordan Conflict

**Comment by sudo-adduser-jordan** [comment]
Updated Video

**Pull request merged**
