### PR TITLE
Fix eslint errors and auth error

### PR DESCRIPTION
**Pull request by devhiko**
---
title: Issue # | Fix auth type error
---

Discord Username: @

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

when you try to contribute project and run `npm run pr-precheck` command, you were seeing a type error related with next-auth at type-check step, now its gone and everything okay.

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings
error

## Added/updated tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## [optional] What gif best describes this PR or how it makes you feel?
- Relaxed

### CODE REVIEW

**Review by FraneCaleta — APPROVED** [review]

**Comment by scape76** [comment]
@devhiko you have some issues

**Comment by devhiko** [comment]
yeah code changed a lot since i pushed this PR.

**Comment by webdevcody** [comment]
failing tests

**Comment by devhiko** [comment]
Ahaha, this merge will last to eternity :D cuz i changed eslint rules and all files have errors now !

**Pull request merged**
