### PR TITLE
#627 | [BUG]: Mobile Phone Keypad Is Not Recognized 

### PR DESCRIPTION
**Pull request by Ragudos**
---
#627 | [BUG]: Mobile Phone Keypad Is Not Recognized 
---

Discord Username: @aaronragudos

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x ] 🐛 Bug Fix
- [x ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

First of all, this pr is only a progress to the bug fix, but rest assured, the only breaking change I've made is removing the textIndicatorPosition state in the race-practice.tsx and race-multiplayer.tsx files. It was unnecessary (I deem it to be) as we are not using arrow keys anymore, and are tracking the text cursor(the highlighted one) based on the current user's input. Also, I fixed a few of esLint and cypress warnings

Second, I added a custom hook that returns a boolean whether a user is on mobile or not based on navigator.userAgent. Please check the lib folder to see it (I did it because navigator is not present in the server).

Third, the initial fixes for the bug on mobile is done. You can now type letters in without a problem.

PROBLEMS LEFT:
 - The enter button in the IMA/mobile keyboard of my phone is considered a keyboard (thus, it has an e.key of "Enter", unlike its siblings of "Unidentified"), so, going to next lines are still impossible right now.

Additionally, I haven't modified the multiplayer textinput yet as the bug needs to be fully fixed first.

Making this PR as I don't want this to be stale, so someone who wants to fix this can also take a look. 

## Related Tickets & Documents

- Related Issue #627 
- Closes #

## QA Instructions, Screenshots, Recordings

1. Use a mobile phone (Specs of the phone I used for testing and where I found out the bug is in the issue).
2. Type something in the race. Now, for this pr, it will look  pretty normal, but try pressing the enter button on your mobile keypad/keyboard.

## Added/updated tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x ] 🙋 no, because I need help

### CODE REVIEW

**Comment by Ragudos** [comment]
currently fixing cypress test error

**Comment by Wirblewind** [comment]
The practice race test seems to fail still, I wouldn't merge until we investigate this.
I thought my PR #630 would fix the problem, but it seems some UI element got changed?
Test keeps failing specifically because it cant find this element:
image

**Comment by Ragudos** [comment]
So, I think instead of separating the endRace logic from the useEffect, we should just put it inside of the useEffect that's calling it. It really causes infinite rerenders if I add in the states that the function endRace is using in its dependencies

**Comment by Ragudos** [comment]
> So, I think instead of separating the endRace logic from the useEffect, we should just put it inside of the useEffect that's calling it. It really causes infinite rerenders if I add in the states that the function endRace is using in its dependencies

Still the same lmao

**Comment by Ragudos** [comment]
> > So, I think instead of separating the endRace logic from the useEffect, we should just put it inside of the useEffect that's calling it. It really causes infinite rerenders if I add in the states that the function endRace is using in its dependencies
> 
> Still the same lmao

So, it was still the same because I was adding in the state, "replayTimeStamp", because I thought it was needed as we are using its setter, setReplayTimeStamp, on the useEffect, Anyway, now, I removed the setReplayTimeStamp since it's already being invoked inside the handleKeyDown event. Additionally, I separated the inputElement.current?.focus since we only want it to happen on page load, not on every change of the user input. Lastly, I removed dependencies on the useEffect for saving results since it will only run if the race has ended (and we want to get everything, like the replayTimeStamp, raceTimeStamp, etc.

**Comment by Ragudos** [comment]
and i just placed the endRace logic inside the useEffect since it is a side-effect

**Comment by Ragudos** [comment]
An error on github test (attribute error, not an error in regards to the result page not loading):
image

Here, everything is fine (able to finish a race):
image

**Comment by Ragudos** [comment]
UPDATE: we can now finish a race.

Here is a summary of everything:

now we can type. Just some bugs left (the interaction of the backspace on mobile is annoying)

Notice how when I press enter then back after I typed two correct characters, it's working, but then it's not after the 2nd backspace. That is because the system is recognizing my backspace as me deleting the existing two characters instead of the /n value of the enter (the value of e.target.value), although I set it up as the setInput deleting the /n value of the enter.

But, when I press a character recognized as a onInput event and not an onKeyboardDown event (remember, the Enter button on my mobile is recognized as an onKeyboardDown event), then everything is back to normal since the input's value is still the same in the first place (the original 2 exisiting characters).

A video demonstration:
https://discord.com/channels/663478877355507769/1128322057088806962/1136072452116586637

**Comment by Ragudos** [comment]
Chores for this if this gets merged:

- Fix the buggy interaction between enter and backspace.
- Refurbish the types as I used any as the parameter types (check race-practice.tsx file)

**Pull request merged**
