### PR TITLE
#545 | open contributor in new tab

### LINKED ISSUE #545: [FEATURE]: (opinionated) open contributor GitHub profile in a new tab
### Feature Summary

Found it a tad annoying when browsing through the profiles. 
IMO the user expectation in this case is to for it to open in a new tab. 

- [ ]  add ` target="_blank"` to make it open in a new tab. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sycodes95**
---
title: Issue # | 545
---

## What type of PR is this? (select all that apply)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Clicking contributor profile or contributor commits now opens in new tab.

## Related Tickets & Documents

- Related Issue #545
- Closes #545

## Added/updated tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by scape76** [comment]
Do you think it's a good ux ? From the user's perspective, he is still on the same website, so it would be confusing if contributors page opened up in a new tab

**Comment by sudo-adduser-jordan** [comment]
This pull request will need another commit to trigger workflow tests.

**Comment by sycodes95** [comment]
> Do you think it's a good ux ? From the user's perspective, he is still on the same website, so it would be confusing if contributors page opened up in a new tab

Oh i'm not talking about the contributors tab, i was talking about when u click contributors profile u are sent to their github page, but i wanted to make it so that their github page opens in a new tab.

**Comment by scape76** [comment]
> > Do you think it's a good ux ? From the user's perspective, he is still on the same website, so it would be confusing if contributors page opened up in a new tab
> 
> Oh i'm not talking about the contributors tab, i was talking about when u click contributors profile u are sent to their github page, but i wanted to make it so that their github page opens in a new tab.

oh, that makes sense

**Pull request merged**
