### PR TITLE
Design Update: Fixed Styling And Layout Issues

### PR DESCRIPTION
**Pull request by aweshchoudhary**
---
title: Issue # |
---

Discord Username: @

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Added new semantic styles and guides and Fixed layout, header, and topbar style issues in all pages and sections
## Related Tickets & Documents

- Related Issue # styles
- Closes #

## Added/updated tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by trace2798** [comment]
@aweshchoudhary Can you provide before and after snaps? Since this PR is not directly related to an Issue.

**Comment by aweshchoudhary** [comment]
Ok, I just fixed the styling issues

**Comment by aweshchoudhary** [comment]
### Before Race Page
before2
### After Race Page
after2
### These Alls are after screenshots (because I getting a login error in the live app)
after5
after4
after3
after1

**Comment by scape76** [comment]
hey, @aweshchoudhary, well done. Can you resolve the conflicts, please?

**Pull request closed without merging**
